language : java
jdk: 
   -openjdk8
   
branches:
   only:
   - main
   
# travis 서버의 home
cache :
   directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'
script : 
   - pwd
   - sudo chmod -R 777 demofront
   - cd demofront
   - ./gradlew clean build

before_deploy:
   
   - cd $HOME/build/jw00n/demoFront
   - pwd
   - mkdir -p before_deploy
   - cp demofront/scripts/*.sh before_deploy/
   - cp appspec.yml before_deploy/
   - cp demofront/build/libs/*.jar before_deploy/
   
   -  pwd
   - cd before_deploy && zip -r before_deploy * 
   
   - pwd
   - cd ../ && mkdir -p deploy
   - mv before_deploy/before_deploy.zip deploy/demo_front.zip
   

deploy:
   - provider: s3
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_KEY
     bucket: momo-demo-build
     region: ap-northeast-2
     skip_cleanup: true
     aci: private
     local_dir: deploy
     wait-until-deployed: true
     on: 
         all_branches: true
         
   - provider: codedeploy
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_KEY
     bucket: momo-demo-build
     key: demo_front.zip
     bundle_type: zip
     application: momo-demoserver
     deployment_group: momo-demofront-group
     region: ap-northeast-2
     wait-until-deployed: true
     on: 
         all_branches: true
    
notifications:
   email:
      recipients:
         - jw00n0212@gmail.com
